# Generated by Django 6.0.7 on 2026-07-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('flagship', 'Flagship'), ('in_progress', 'In progress'), ('side', 'Side project')], default='side', help_text='Бейдж, который показывается на карточке проекта', max_length=20),
        ),
    ]
