# Generated by Django 6.0.7 on 2026-07-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skill_options_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Текст ссылки, например: you@forskie.top или @Forck1e', max_length=100)),
                ('url', models.CharField(help_text='Полный адрес. Примеры: mailto:you@example.com · https://github.com/username · https://t.me/username · https://wa.me/992908204646 · tel:+992908204646 · https://leetcode.com/u/username', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Контактная ссылка',
                'verbose_name_plural': 'Контактные ссылки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Например: Safolov Biloliddin', max_length=200)),
                ('role_title', models.CharField(blank=True, help_text='Например: Backend Engineer', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Например: Dushanbe, Tajikistan', max_length=200)),
                ('availability', models.CharField(blank=True, help_text='Например: Open to Remote (можно оставить пустым)', max_length=200)),
                ('thesis', models.TextField(blank=True, help_text='Короткий питч под именем в hero. Можно оборачивать важные слова в <strong>...</strong> — они выделятся цветом.')),
                ('currently_text', models.TextField(blank=True, help_text="Текст секции 'Currently' внизу страницы. Можно использовать <strong>...</strong>.")),
                ('resume', models.FileField(blank=True, help_text="Загрузи PDF — ссылка 'resume.pdf' в шапке будет вести на него", null=True, upload_to='resume/')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
