# Generated by Django 6.0.7 on 2026-07-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactlink_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('education', 'Education'), ('certification', 'Certification'), ('achievement', 'Achievement')], max_length=20)),
                ('title', models.CharField(help_text='E.g. B.Sc. Computer Science, or AWS Certified Developer', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='E.g. institution or issuing organization', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, help_text='Leave blank for ongoing / no end date.', null=True)),
                ('url', models.URLField(blank=True, help_text='Optional link, e.g. to a credential or certificate.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
                'ordering': ['order', '-date_start'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Used for the meta description and social previews. If left blank, profile.thesis is used instead.')),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('og_image', models.ImageField(blank=True, help_text='Image shown when the site is shared on social media (recommended 1200x630).', null=True, upload_to='seo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('twitter_handle', models.CharField(blank=True, help_text='E.g. @username (leave blank to omit)', max_length=100)),
                ('canonical_url', models.URLField(blank=True, help_text='Full site URL, e.g. https://example.com. If blank, the current request URL is used.')),
                ('footer_text', models.CharField(blank=True, help_text="Overrides the default footer text. If blank, shows '© {year} {full name}'.", max_length=300)),
                ('show_deployment_panel', models.BooleanField(default=False, help_text="Show an optional 'deployment status' panel in the footer.")),
                ('deployment_host', models.CharField(blank=True, max_length=100)),
                ('deployment_server', models.CharField(blank=True, max_length=100)),
                ('deployment_runtime', models.CharField(blank=True, max_length=100)),
                ('deployment_database', models.CharField(blank=True, max_length=100)),
                ('deployment_proxy', models.CharField(blank=True, max_length=100)),
                ('deployment_shipped_via', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AlterModelOptions(
            name='contactlink',
            options={'ordering': ['order'], 'verbose_name': 'Contact link', 'verbose_name_plural': 'Contact links'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-date_start'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experience'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='contactlink',
            name='icon',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('website', 'Website'), ('link', 'Generic link')], default='link', help_text='Which icon to show next to the label.', max_length=20),
        ),
        migrations.AddField(
            model_name='contactlink',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary buttons are styled as solid/filled (use for one main CTA, e.g. Email).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional headshot for the hero. Square images (min 480x480) work best.', null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional small square logo, shown next to the title instead of a thumbnail.', null=True, upload_to='projects/logos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional cover image, shown at the top of the card (recommended 16:9).', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='label',
            field=models.CharField(help_text='Button text, e.g. you@example.com or @username', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='url',
            field=models.CharField(help_text='Full address. Examples: mailto:you@example.com · https://github.com/username · https://t.me/username · https://wa.me/15551234567 · tel:+15551234567', max_length=300),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_end',
            field=models.DateField(blank=True, help_text="Leave blank for 'Present'.", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(blank=True, help_text='E.g. Open to remote work (leave blank to hide)', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currently_text',
            field=models.TextField(blank=True, help_text="Text for the 'Currently' section. <strong>...</strong> is supported."),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, help_text='E.g. Jane Doe', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='E.g. Dushanbe, Tajikistan (leave blank to hide)', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text="Upload a PDF — the 'Resume' button in the hero will link to it.", null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role_title',
            field=models.CharField(blank=True, help_text='E.g. Backend Engineer', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thesis',
            field=models.TextField(blank=True, help_text='Short pitch under the name in the hero. Wrap key words in <strong>...</strong> to highlight them in accent color.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('flagship', 'Flagship'), ('in_progress', 'In progress'), ('side', 'Side project')], default='side', help_text='Badge shown on the project card.', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated, e.g. Django, PostgreSQL, Redis', max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional, 1-5. Leave blank to hide the level indicator for this skill.', null=True),
        ),
    ]
